/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconMdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
    IconMdiAccountPlusOutline: typeof import('~icons/mdi/account-plus-outline')['default']
    IconMdiChefHat: typeof import('~icons/mdi/chef-hat')['default']
    IconMdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiLockOutline: typeof import('~icons/mdi/lock-outline')['default']
    IconMdiLockReset: typeof import('~icons/mdi/lock-reset')['default']
    IconMdiRobotExcitedOutline: typeof import('~icons/mdi/robot-excited-outline')['default']
    IconMdiShieldKeyOutline: typeof import('~icons/mdi/shield-key-outline')['default']
    NutCalendarCard: typeof import('@nutui/nutui')['CalendarCard']
    NutInfiniteLoading: typeof import('@nutui/nutui')['InfiniteLoading']
    NutPullRefresh: typeof import('@nutui/nutui')['PullRefresh']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
  }
}
